apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: voting-app
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env"
      value:
        - name: DB_HOST
          value: "db.voting-app"
        - name: REDIS_HOST
          value: "redis.voting-app"
    - op: add
      path: "/spec/template/spec/initContainers/0/env"
      value:
        - name: DB_HOST
          value: "db.voting-app"
        - name: REDIS_HOST
          value: "redis.voting-app"
  target:
    kind: Deployment