apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- vote-svc.yaml
- vote-svc-preview.yaml
namespace: voting-app
patches:
- path: vote-ro-bg.yaml
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env"
      value:
        - name: REDIS_HOST
          value: "redis.voting-app"
    - op: add
      path: "/spec/template/spec/initContainers/0/env"
      value:
        - name: REDIS_HOST
          value: "redis.voting-app"
  target:
    kind: Rollout