apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: result
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - cluster: staging
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'result-{{.cluster}}'
      namespace: argocd
      annotations:
        kargo.akuity.io/authorized-stage: voting-app:vote-{{.cluster}}
    spec:
      project: voting-app
      source:
        repoURL: https://github.com/tw0-face/yava.git
        targetRevision: main
        path: manifests/app/result/overlays/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: voting-app
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            elbv2.k8s.aws/pod-readiness-gate-inject: enabled