apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: voting-app
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env"
      value:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: voting-app-db-conn-cm
              key: "voting-app.voting-app-db-host"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: voting-app-redis-conn-cm
              key: "voting-app.voting-app-redis-host"
    - op: add
      path: "/spec/template/spec/initContainers/0/env"
      value:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: voting-app-redis-conn-cm
              key: "voting-app.voting-app-redis-host"
    - op: add
      path: "/spec/template/spec/initContainers/1/env"
      value:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: voting-app-db-conn-cm
              key: "voting-app.voting-app-db-host"
  target:
    kind: Deployment