apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      initContainers:
      - name: wait-for-redis
        image: redis
        command: ["/bin/sh", "-c"]
        args:
        - |
          HOST="${REDIS_HOST:-redis}"
          echo "Waiting for Redis at $HOST..."
          until redis-cli -h "$HOST" ping | grep -q PONG; do
            echo "Redis not ready, retrying..."
            sleep 2
          done
          echo "Redis is ready."
      containers:
      - name: vote
        image: annamartin123/vote:c57c36c
        ports:
        - containerPort: 80
          name: vote
  strategy: {}