apiVersion: v1
kind: Service
metadata:
  name: localstack-dns
  namespace: localstack
spec:
  type: NodePort
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30553
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30553
  selector:
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/name: localstack