apiVersion: v1
stringData:
  .dockerconfigjson: '{"auths":{"https://index.docker.io/v1/":{"username":"","password":"","email":"","auth":""}}}'
kind: Secret
metadata:
  name: regcred
  namespace: argo
type: kubernetes.io/dockerconfigjson
