apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tw0-face/yava.git
    targetRevision: main
    path: manifests/configs/argowf
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true